services:
  # Backend Service
  - type: web
    name: theratime-backend
    env: docker
    rootDir: backend
    plan: free
    branch: main
    envVars:
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false

  # Frontend Service
  - type: web
    name: theratime-frontend
    env: static
    rootDir: frontend
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
    envVars:
      - key: VITE_BASE_URL
        fromService:
          type: web
          name: theratime-backend
          property: url
